mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http  import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
# Create your views here.

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name='polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions (not including those set to be published in the future)."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
        <title>Polls Application</title>

        <!-- CSS  -->
        <link rel="stylesheet" type="text/css" href="{% static 'polls/materialize/css/materialize.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'polls/materialize/css/materialize.css' %}">
        
    </head>
    <body>
                {% include "polls/header.html" %}
                <div class="section no-pad-bot" id="index-banner">
                    <div class="container">
                        {% block main_content%}

                        {% endblock %}
                    </div>
                  </div>
                
                {% include "polls/footer.html" %}
    </body>
</html>

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block main_content %}
<p> <a href="{% url 'polls:index' %}">Back to Questions!</a></p>
<h1 class="center">{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post" class="center">
{% csrf_token %}
{% for choice in question.choice_set.all %}

    
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}"> {{ choice.choice_text }}</label><br>

{% endfor %}
<br>
<div class="row">
    <div class="col-md-6">
        <button class="center" style="background-color:aquamarine; font-size: 20px; padding: 10px; border-radius: 8px;"> Vote</button>
    </div>
    

    
</div>

</form> 
<br><br><br><br><br><br><br><br><br>
{% endblock %}

mysite/polls/templates/polls/footer.html
<footer class="page-footer orange">
    <div class="footer-copyright">
      <div class="container center">
      Polling Application for you
      <br>
      </div>
    </div>
  </footer>

mysite/polls/templates/polls/header.html
<nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Polling Site</a>
    </div>
  </nav>
  

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block main_content %}
<br><br>
<h1 class="header center orange-text">Select Question?</h1>
<div class="row center">
    <h5 class="header col s12 light">
        {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            <br><br><br>
            {% endfor %}
        </ul>    
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </h5>
</div>
{% endblock%}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block main_content %}
<p> <a href="{% url 'polls:index' %}">Back to Questions!</a></p>
<br>
<h1>{{ question.question_text }}</h1>
<br>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li> <br><br>
    <br>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<br> <br>  <br>  <br>  <br>  <br>  <br>  <br>  <br>
{% endblock %}